# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish new release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Upload coverage
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{secrets.CODACY_ACCESS_KEY}}
          coverage-reports: './coverage/ngx-onscreen-twelvekeyboard/lcov.info'

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish ./dist/ngx-onscreen-twelvekeyboard
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_KEY}}
